# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Compile
      run: |
          javac Test.java
          java Test
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: artifact
        path: Test.class
  deployDEV:
    environment: 'dev'
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.1
      with:
        # Artifact name
        name: artifact
    - run: java Test
  deployQUA:
    environment: 'qua'
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.1
      with:
        # Artifact name
        name: artifact
    - run: java Test
